brief_file_path: null
brief_parsed: false
campaign_type: digital
client: Ueno Bank
country: Paraguay
created_at: '2025-11-24T20:04:09.925713Z'
id: campana-ueno-bank-paraguay-2025
ideas_count: 3
language: es
name: Campaña Ueno Bank Paraguay
status: ideas_generated
updated_at: '2025-11-24T21:53:35.036645Z'
