brief_file_path: null
brief_parsed: false
campaign_type: digital
client: Nestle
country: Paraguay
created_at: '2025-11-25T13:53:01.771158Z'
id: campana-nestle-paraguay
ideas_count: 15
language: es
name: Campaña Nestle Paraguay
status: ideas_generated
updated_at: '2025-11-25T14:04:59.455450Z'
