import asyncio
import sys
import os
from unittest.mock import AsyncMock, MagicMock, patch

# Add code directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

# Mock dependencies
sys.modules["google"] = MagicMock()
sys.modules["google.generativeai"] = MagicMock()
sys.modules["google.api_core"] = MagicMock()
sys.modules["google.api_core.exceptions"] = MagicMock()
sys.modules["gpt_researcher"] = MagicMock()
sys.modules["langfuse"] = MagicMock()
sys.modules["langfuse.callback"] = MagicMock()

# Mock langchain to avoid debug attribute error
mock_langchain = MagicMock()
mock_langchain.debug = False
sys.modules["langchain"] = mock_langchain

from api.graphs.campaign_graph import CampaignGraphRunner

async def test_graph_with_gpt_researcher():
    print("Starting test_graph_with_gpt_researcher...")
    
    # Mock dependencies
    with patch("api.graphs.campaign_graph.get_ai_manager") as mock_get_ai, \
         patch("api.graphs.campaign_graph.get_research_service") as mock_get_research, \
         patch("api.graphs.campaign_graph.get_gpt_research_service") as mock_get_gpt_research, \
         patch("api.graphs.campaign_graph.get_campaign_memory_lazy") as mock_get_memory:
        
        # Setup Memory Mock
        mock_memory = AsyncMock()
        mock_get_memory.return_value = mock_memory
        
        # Setup AI Mock
        mock_ai = AsyncMock()
        mock_ai.generate.return_value = "Synthesized insights from GPT research."
        mock_ai.generate_json.return_value = {"ideas": [{"title": "Test Idea", "description": "Test Desc", "rationale": "Test Rat"}]}
        mock_get_ai.return_value = mock_ai
        
        # Setup Research Service Mock (return empty to trigger GPT Researcher)
        mock_research = AsyncMock()
        mock_research.get_all_research.return_value = "" 
        mock_get_research.return_value = mock_research
        
        # Setup GPT Researcher Mock
        mock_gpt = AsyncMock()
        mock_gpt.conduct_research.return_value = "Deep research report generated by GPT Researcher."
        mock_get_gpt_research.return_value = mock_gpt
        
        print("Initializing runner...")
        runner = CampaignGraphRunner()
        
        print("Running campaign...")
        result = await runner.run_campaign("test-project")
        
        print("Verifying results...")
        # Verify GPT Researcher was called
        mock_gpt.conduct_research.assert_called_once()
        print("GPT Researcher was called successfully.")
        
        # Verify result contains research data
        # Note: The graph state might not directly expose the research data in the final output 
        # depending on how the graph is compiled, but we verified the call.
        
        print("Test passed successfully!")

if __name__ == "__main__":
    try:
        asyncio.run(test_graph_with_gpt_researcher())
    except Exception as e:
        print(f"Test failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
